### PR TITLE
feat(options): populate isRouted and isRecorded from options

### PR DESCRIPTION
**Pull request by Guria**

### CODE REVIEW

**Comment by Guria** [comment]
@christianalfoni please clarify iintention here. Didn't get why signal store aware of `isRouted` and `isRecorded`.

**Comment by christianalfoni** [comment]
It is for the debugger. It should indicate if a signal is routed. Currently it does not indicate that a signal triggered is recorded, but now it can :-)

The change is due to these options now being available on the options object only, instead of the signal itself. Change https://github.com/cerebral/cerebral/pull/237/commits/009f02845b501c1b23ca5d4fef3d0e806935a0c1

**Comment by Guria** [comment]
Ahh. OK. I like that "special" options knowledge moved to signal store.

**Comment by christianalfoni** [comment]
Yup, me too :D

**Comment by Guria** [comment]
LGTM

**Pull request merged**
